project:
  type: website
  resources:
    - CNAME
  output-dir: docs
  
website:
  title: "Manh ND"
  favicon: "img/profile.png"
  navbar:
    background: primary
    left:
      - text: Home
        href: index.qmd
      - text: Material
        href: material/index.qmd
      - projects.qmd
    right:
      - icon: github
        href: https://github.com/manhnguy
      - icon: linkedin
        href: https://www.linkedin.com/in/manh-nguyen-duc-460362257/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, manhnd"

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true

comments:
  giscus:
    repo: manhnguy/manhnguy.github.io

